# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_calc_entropy')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_calc_entropy')
    _calc_entropy = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_calc_entropy', [dirname(__file__)])
        except ImportError:
            import _calc_entropy
            return _calc_entropy
        if fp is not None:
            try:
                _mod = imp.load_module('_calc_entropy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _calc_entropy = swig_import_helper()
    del swig_import_helper
else:
    import _calc_entropy
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _calc_entropy.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _calc_entropy.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _calc_entropy.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _calc_entropy.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _calc_entropy.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _calc_entropy.SwigPyIterator_equal(self, x)

    def copy(self):
        return _calc_entropy.SwigPyIterator_copy(self)

    def next(self):
        return _calc_entropy.SwigPyIterator_next(self)

    def __next__(self):
        return _calc_entropy.SwigPyIterator___next__(self)

    def previous(self):
        return _calc_entropy.SwigPyIterator_previous(self)

    def advance(self, n):
        return _calc_entropy.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _calc_entropy.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _calc_entropy.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _calc_entropy.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _calc_entropy.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _calc_entropy.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _calc_entropy.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _calc_entropy.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _calc_entropy.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _calc_entropy.VecDouble___nonzero__(self)

    def __bool__(self):
        return _calc_entropy.VecDouble___bool__(self)

    def __len__(self):
        return _calc_entropy.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _calc_entropy.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _calc_entropy.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _calc_entropy.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _calc_entropy.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _calc_entropy.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _calc_entropy.VecDouble___setitem__(self, *args)

    def pop(self):
        return _calc_entropy.VecDouble_pop(self)

    def append(self, x):
        return _calc_entropy.VecDouble_append(self, x)

    def empty(self):
        return _calc_entropy.VecDouble_empty(self)

    def size(self):
        return _calc_entropy.VecDouble_size(self)

    def swap(self, v):
        return _calc_entropy.VecDouble_swap(self, v)

    def begin(self):
        return _calc_entropy.VecDouble_begin(self)

    def end(self):
        return _calc_entropy.VecDouble_end(self)

    def rbegin(self):
        return _calc_entropy.VecDouble_rbegin(self)

    def rend(self):
        return _calc_entropy.VecDouble_rend(self)

    def clear(self):
        return _calc_entropy.VecDouble_clear(self)

    def get_allocator(self):
        return _calc_entropy.VecDouble_get_allocator(self)

    def pop_back(self):
        return _calc_entropy.VecDouble_pop_back(self)

    def erase(self, *args):
        return _calc_entropy.VecDouble_erase(self, *args)

    def __init__(self, *args):
        this = _calc_entropy.new_VecDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _calc_entropy.VecDouble_push_back(self, x)

    def front(self):
        return _calc_entropy.VecDouble_front(self)

    def back(self):
        return _calc_entropy.VecDouble_back(self)

    def assign(self, n, x):
        return _calc_entropy.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _calc_entropy.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _calc_entropy.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _calc_entropy.VecDouble_reserve(self, n)

    def capacity(self):
        return _calc_entropy.VecDouble_capacity(self)
    __swig_destroy__ = _calc_entropy.delete_VecDouble
    __del__ = lambda self: None
VecDouble_swigregister = _calc_entropy.VecDouble_swigregister
VecDouble_swigregister(VecDouble)


def print_matrix(m):
    return _calc_entropy.print_matrix(m)
print_matrix = _calc_entropy.print_matrix

def construct_F(phi1, phi2, F):
    return _calc_entropy.construct_F(phi1, phi2, F)
construct_F = _calc_entropy.construct_F

def diag_F(F, Q, F_bd):
    return _calc_entropy.diag_F(F, Q, F_bd)
diag_F = _calc_entropy.diag_F

def max_val(m):
    return _calc_entropy.max_val(m)
max_val = _calc_entropy.max_val

def entropy(phi1, phi2, flips, digits):
    return _calc_entropy.entropy(phi1, phi2, flips, digits)
entropy = _calc_entropy.entropy

def get_corr_matrix(flips, Q, C):
    return _calc_entropy.get_corr_matrix(flips, Q, C)
get_corr_matrix = _calc_entropy.get_corr_matrix
# This file is compatible with both classic and new-style classes.


